version: '3.1'
services:
  plant_sensor_endpoints_test:
    build: .
    container_name: plant_sensor_endpoints_test
    volumes:
    - ./:/app
    networks:
      - plant_sensor_endpoints_test
    stdin_open: true
    tty: true
    #entrypoint: scripts/support/pytest.sh
    entrypoint: bash
    depends_on:
      - plant_sensor_db_test
    environment:
      - SQLALCHEMY_URL='postgres://plant_sensor_endpoint/plant_sensor_endpoint@plant_sensor_db:5432/plant_sensor_endpoint'
  plant_sensor_db_test:
    container_name: plant_sensor_db_test
    image: postgres:12.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts/support/init-db.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - plant_sensor_endpoints_test
networks:
  plant_sensor_endpoints_test:
    driver: bridge